// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-tangra/go-tangra-backup/internal/cert"
	"github.com/go-tangra/go-tangra-backup/internal/server"
	"github.com/go-tangra/go-tangra-backup/internal/service"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
)

// Injectors from wire.go:

// initApp initializes the Wire provider entry for the kratos application
func initApp(context *bootstrap.Context) (*kratos.App, func(), error) {
	certManager, err := cert.NewCertManager(context)
	if err != nil {
		return nil, nil, err
	}
	moduleClient := service.NewModuleClient(context)
	backupStorage := service.NewBackupStorage(context)
	orchestratorService := service.NewOrchestratorService(context, moduleClient, backupStorage)
	grpcServer := server.NewGRPCServer(context, certManager, orchestratorService)
	httpServer := server.NewHTTPServer(context)
	app := newApp(context, grpcServer, httpServer)
	return app, func() {
	}, nil
}
